name: Cypress CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # 👈 Mudamos de 18 para 20

      - name: Instalar dependências
        run: npm install
        working-directory: ./automation

      - name: Rodar testes Cypress
        run: npx cypress run
        working-directory: ./automation